ASM=../../bin/asm
ACSE=../../bin/acse
objects=$(patsubst %.src,%.o,$(wildcard *.src))

test : $(objects)

%.o : %.asm
	$(ASM) $< $@	

%.asm : %.src
	$(ACSE) $< $@

.PRECIOUS : %.asm

.PHONY : clean test

clean :
	rm -f *.out
	rm -f *.cfg
	rm -f *.asm
	rm -f *.o
