ASM=../../bin/asm
ACSE=../../bin/acse
objects=$(patsubst %.src,%.o,$(wildcard *.src))
# add .exe at the end on Windows
asm_file=$(wildcard $(ASM)*)
acse_file=$(wildcard $(ACSE)*)

test : $(objects)

%.o: %.asm $(asm_file)
	$(ASM) $< $@

%.asm: %.src $(acse_file)
	$(ACSE) $< $@

.PRECIOUS : %.asm

.PHONY : clean test 

clean :
	rm -f *.log
	rm -f *.asm
	rm -f *.o
