ASM=../../bin/asm
ACSE=../../bin/acse
objects=$(patsubst %.src,%.o,$(wildcard *.src))
# add .exe at the end on Windows
asm_file=$(wildcard $(ASM)*)
acse_file=$(wildcard $(ACSE)*)

.PHONY: test
ifeq (,$(wildcard _NO_TEST_))
# the '_NO_TEST_' file does not exist
test: $(objects)
else
# the '_NO_TEST_' file does exist
test:
	@echo 'info: tests in directory "$(notdir $(shell pwd))" skipped'
endif

%.o: %.asm $(asm_file)
	$(ASM) $< $@

.PRECIOUS: %.asm
%.asm: %.src $(acse_file)
	$(ACSE) $< $@

.PHONY: clean 
clean :
	rm -f *.log *.asm *.o
